# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main,dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Details can be seen here: https://github.com/actions/checkout
      - name: Checkout Step
        uses: actions/checkout@v4
      
      - name: Copy files to dist
        run: |
          scripts/build.sh
      - name: Set remote path
        id: set_path
        run: |
          echo "Current branch is: ${{ github.ref_name }}"
         
          if [ "${{ github.ref_name }}" = "main" ]; then
            REMOTE_PATH=${{ vars.REMOTE_PATH_PROD }}
          else
            REMOTE_PATH=${{ vars.REMOTE_PATH_DEV }}
          fi

          echo "REMOTE_PATH=$REMOTE_PATH" >> $GITHUB_ENV
          echo "Remote path: $REMOTE_PATH"
 
      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -rlpcgoDv --delete
          path: dist/
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ vars.SSH_HOSTNAME }}
          remote_port: ${{ vars.SSH_PORT }} 
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Are files still in dist
        run: |
          echo "Contents:"
          mkdir public
          cp dist/* public/
          ls -Rl
      - name: Deploy to GitHub Pages
        if: ${{ github.ref_name == 'main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: prod
